### PR TITLE
Fix town names on regional map

### PR DESCRIPTION
**Pull request by EugeneLesnov**
There was an issue on displaying long town names like "Taur-Im-Duinath". Town name just did not fit on map.
Here's possible solution:
wide map

P.S. Additional commits just to clean up the code, suggested by the static analyzer of CLion.

### CODE REVIEW

**Comment by EugeneLesnov** [comment]
Another thoughts on regional map..How about getting rid of the words like "Plain" or "Forest" ?

I can implement mapping locality with color. At the bottom we can describe what color means like "green - forest, umber - plain".
mapping locality with color

**Comment by NickMcConnell** [comment]
This is pretty much exactly what I wanted to do, so if you want to implement that that's great.  I don't want the commented code removed though - that's a reminder to me that I have to fix something.

**Comment by NickMcConnell** [comment]
In fact, I've pulled most of this in by cherry-pick, so I'll close this.  But I would very much like to see another pull request with the code that produced your second screenshot.

**Comment by NickMcConnell** [comment]
Actually don't worry, I'm going to do this.  Thanks for the ideas 😄

**Comment by NickMcConnell** [comment]
Done in the latest commit 👍

**Comment by EugeneLesnov** [comment]
@NickMcConnell Great!

**Pull request closed without merging**
