### PR TITLE
Added Witch tile to Gervais tile sheet plus reference

### PR DESCRIPTION
**Pull request by davidk64fnq**
Witch

Witch tile sourced from Tangaria tile sheet https://tangaria.com/tileset/

(The large number of commits for this simple pull request is likely me forgetting to rebase my branch before I started)

### CODE REVIEW

**Comment by davidk64fnq** [comment]
Does this have to wait for next release now? There is an error in the Weasel tile reference and also I have other tile additions pending but waiting to rebase my branch first.

**Comment by NickMcConnell** [comment]
This shouldn't have to wait for another release, but I would recommend collecting a number of tile changes together doing a single pull request with them, rather than changing the whole tile sheet every time there's a new tile added.

**Comment by davidk64fnq** [comment]
Is there another step I have to do to get this completed then?

**Comment by NickMcConnell** [comment]
I would recommend:

1. Make a branch which tracks the main branch
2. Make another branch which has your tile additions on it
3. Update your main tracking branch, and then rebase your tile branch, any time you're going to add a new tile
This way you can accumulate tile additions, and then make a pull request when you're ready.  I'm recommending this for a variety of reasons, some of them selfish 😄

**Pull request closed without merging**
